ENVIRONMENT:
  MAX_EPISODE_STEPS: 500
  ITERATOR_OPTIONS:
    MAX_SCENE_REPEAT_STEPS: 50000
SIMULATOR:
  TURN_ANGLE: 30
  FORWARD_STEP_SIZE: 0.25
  AGENT_0:
    SENSORS: ["RGB_SENSOR"]
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
  RGB_SENSOR:
    WIDTH: 256
    HEIGHT: 256
    HFOV: 90
  DEPTH_SENSOR:
    WIDTH: 256
    HEIGHT: 256
    HFOV: 90
TASK:
  TYPE: Nav-v0
  POSSIBLE_ACTIONS: ["MOVE_FORWARD", "TURN_LEFT", "TURN_RIGHT"]
  SUCCESS_DISTANCE: 0.5

  SENSORS: ['CUBE_RGB_SENSOR','CUBE_IMAGEGOAL_SENSOR']
  GOAL_SENSOR_UUID: panoramic_image_goal

  MEASUREMENTS: ["DISTANCE_TO_GOAL", "SUCCESS", "SPL"]
  DISTANCE_TO_GOAL:
    DISTANCE_TO: POINT
  SUCCESS:
    SUCCESS_DISTANCE: 0.5

DATASET:
  TYPE: PointNav-v1
  SPLIT: train
  DATA_PATH: data/datasets/pointnav/mp3d/v1/{split}/{split}.json.gz
