ENVIRONMENT:
  MAX_EPISODE_STEPS: 1000
  ITERATOR_OPTIONS:
    MAX_SCENE_REPEAT_STEPS: 25000
SIMULATOR:
  AGENT_0:
    SENSORS: ["RGB_SENSOR"]
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 2
  RGB_SENSOR:
    WIDTH: 256
    HEIGHT: 256
  DEPTH_SENSOR:
    WIDTH: 256
    HEIGHT: 256
TASK:
  TYPE: Nav-v0
  SUCCESS_DISTANCE: 1.

  SENSORS: ['PANORAMIC_RGB_SENSOR','PANORAMIC_IMAGEGOAL_SENSOR']
  GOAL_SENSOR_UUID: panoramic_image_goal

  MEASUREMENTS: ["DISTANCE_TO_GOAL", "SUCCESS", "SPL"]
  SUCCESS:
    SUCCESS_DISTANCE: 1.

DATASET:
  TYPE: PointNav-v1
  SPLIT: train
  DATA_PATH: data/datasets/pointnav/mp3d/v1/{split}/{split}.json.gz
